public_gsheets_url = "https://docs.google.com/spreadsheets/d/1DV7JbHuxqdm9dZicVFXurYN1NGdUoK_Lcohp7h3Ec9k/edit#gid=597357721"

public_gsheets_url1 = "https://docs.google.com/spreadsheets/d/1DV7JbHuxqdm9dZicVFXurYN1NGdUoK_Lcohp7h3Ec9k/edit#gid=458035789"